version: '2'

services:
  db:
    image: bitnami/postgresql:10
    volumes:
      - ./.pgdata:/bitnami
      - ./migrations:/migrations
    ports:
      - "5432:5432"
    env_file: docker-app-dev/.env

  # postgraphile:
  #   build:
  #     context: ./docker-app-dev
  #     dockerfile: Dockerfile.postgraphile
  #   ports:
  #     - "5000:5000"
  #   env_file: docker-app-dev/.env
  #   depends_on:
  #     - db

  # nuxt:
  #   build:
  #     context: ./docker-app-dev
  #     dockerfile: Dockerfile.web
  #   ports:
  #    - "3000:3000"
  #   volumes:
  #     - .:/app
  #   env_file: docker-app-dev/.env
  #   depends_on:
  #     - db
  #     - postgraphile
